name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: welcome_test1

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Stop existing container
        run: docker stop my-web-app-container || true

      - name: Remove existing container
        run: docker rm my-web-app-container || true

      - name: Remove existing image
        run: docker rmi my-web-app:latest || true

      - name: Build Docker image
        run: docker build -t my-web-application:latest .

      - name: Run container
        run: docker run -d --name my-web-app-container -p 8090:80 my-web-application:latest
